I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 797, in script
    aya "Ça va bien et toi ?"
Exception: Sayer 'aya' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 797, in script
    aya "Ça va bien et toi ?"
  File "/Applications/Renpy/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/Renpy/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'aya' is not defined.

Darwin-21.1.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
RGUIG GAME 1.0
Tue Aug  2 17:41:13 2022
